import {
  ArrowRight,
  Award,
  Baby,
  BadgeCheck,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Briefcase,
  BriefcaseBusiness,
  BookOpen,
  Building2,
  Camera,
  Clock,
  Eye,
  FileText,
  Film,
  Frown,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  HelpCircle,
  Info,
  Lightbulb,
  List,
  Megaphone,
  MessageCircle,
  Mic,
  MicOff,
  Meh,
  Music,
  PlayCircle,
  Radio,
  Shuffle,
  Smile,
  Sparkles,
  Star,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  UserCheck,
  Video,
  Volume2,
  Zap,
  ShoppingCart,
} from "lucide-react";

import { QuizQuestionData } from "./quizTypes";

export const QUIZ_QUESTIONS: QuizQuestionData[] = [
  {
    key: "age_range",
    question: "Quantos anos voc? tem?",
    options: [
      { value: "under_18", label: "At? 18 anos", icon: Baby },
      { value: "18_24", label: "18?24", icon: GraduationCap },
      { value: "25_34", label: "25?34", icon: Briefcase },
      { value: "35_44", label: "35?44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "gender",
    question: "Qual o seu g?nero?",
    options: [
      { value: "woman", label: "Mulher", icon: Heart },
      { value: "man", label: "Homem", icon: UserCheck },
      { value: "non_binary", label: "N?o-bin?rio", icon: Users },
      { value: "prefer_not", label: "Prefiro n?o informar", icon: HelpCircle },
    ],
  },
  {
    key: "main_goal",
    question: "Qual ? o seu principal objetivo?",
    options: [
      { value: "more_followers", label: "+ Seguidores", icon: TrendingUp },
      { value: "more_views", label: "+ Visualiza??es", icon: Eye },
      { value: "more_engagement", label: "Maior engajamento", icon: Heart },
      { value: "more_messages_sales", label: "Receber mais mensagens/vendas", icon: MessageCircle },
    ],
  },
  {
    key: "comfort_recording",
    question: "Como voc? se sente ao gravar v?deos?",
    options: [
      { value: "sometimes_insecure", label: "?s vezes fico inseguro", icon: Meh },
      { value: "freeze_lose_words", label: "Costumo travar ou perder palavras", icon: Frown },
      { value: "avoid", label: "Evito gravar sempre que posso", icon: MicOff },
      { value: "very_uncomfortable", label: "Muito desconfort?vel", icon: BatteryLow },
    ],
  },
  {
    key: "biggest_challenge",
    question: "Qual ? o maior desafio que voc? enfrenta hoje com v?deos?",
    options: [
      { value: "lack_ideas", label: "Faltar ideias de conte?do", icon: Lightbulb },
      { value: "poor_editing", label: "N?o saber editar bem", icon: Film },
      { value: "no_engagement", label: "N?o conseguir engajar o p?blico", icon: Users },
      { value: "shyness", label: "Timidez / falta de confian?a ao falar", icon: Mic },
    ],
  },
  {
    key: "planning_style",
    question: "Como voc? planeja seus v?deos?",
    options: [
      { value: "no_technique", label: "Fa?o roteiros sem t?cnica", icon: FileText },
      { value: "loose_topics", label: "Tenho apenas t?picos soltos", icon: List },
      { value: "no_script", label: "Vou gravando sem roteiro", icon: Video },
      { value: "watch_others", label: "Vejo outros v?deos", icon: PlayCircle },
    ],
  },
  {
    key: "editing_time",
    question: "Quanto tempo voc? dedica ? grava??o?",
    options: [
      { value: "less_30min", label: "Menos de 30 min por v?deo", icon: Timer },
      { value: "30min_1h", label: "30 min ? 1h", icon: Clock },
      { value: "1_2h", label: "1?2h", icon: BatteryMedium },
      { value: "more_2h", label: "Mais de 2h", icon: BatteryFull },
    ],
  },
  {
    key: "niche",
    question: "Sobre o que voc? gosta de falar?",
    options: [
      { value: "education", label: "Educa??o / Conte?do informativo", icon: BookOpen },
      { value: "business", label: "Neg?cios / Marketing / Vendas", icon: BriefcaseBusiness },
      { value: "lifestyle", label: "Lifestyle / Rotina / Vlogs", icon: Heart },
      { value: "health", label: "Sa?de / Fitness / Bem-estar", icon: HeartPulse },
      { value: "entertainment", label: "Entretenimento / Humor", icon: Film },
      { value: "other", label: "Outro / Ainda estou definindo", icon: Sparkles },
    ],
  },
  {
    key: "creator_level",
    question: "Qual ? o seu n?vel como criador de conte?do?",
    options: [
      { value: "beginner", label: "Iniciante (come?ando na ?rea)", icon: Trophy },
      { value: "basic", label: "B?sico (j? postei alguns v?deos)", icon: Award },
      { value: "intermediate", label: "Intermedi?rio (posto com frequ?ncia)", icon: Star },
      { value: "advanced", label: "Avan?ado (crio conte?do profissionalmente)", icon: BadgeCheck },
    ],
  },
  {
    key: "audience_type",
    question: "Quem ? sua audi?ncia principal?",
    options: [
      { value: "b2c", label: "Pessoas f?sicas (B2C)", icon: Users },
      { value: "entrepreneurs", label: "Empreendedores / Profissionais", icon: BriefcaseBusiness },
      { value: "creators", label: "Criadores de conte?do", icon: Sparkles },
      { value: "b2b", label: "Empresas (B2B)", icon: Building2 },
      { value: "general", label: "P?blico geral", icon: Globe },
    ],
  },
  {
    key: "audience_age",
    question: "Qual ? a faixa et?ria do seu p?blico?",
    options: [
      { value: "under_18", label: "At? 18 anos", icon: Baby },
      { value: "18_24", label: "18?24", icon: GraduationCap },
      { value: "25_34", label: "25?34", icon: Briefcase },
      { value: "35_44", label: "35?44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "audience_gender",
    question: "Como ? a distribui??o de g?nero do seu p?blico?",
    options: [
      { value: "mostly_female", label: "Majoritariamente feminino", icon: Heart },
      { value: "mostly_male", label: "Majoritariamente masculino", icon: UserCheck },
      { value: "balanced", label: "Bem equilibrado", icon: Users },
      { value: "unknown", label: "Ainda n?o sei", icon: HelpCircle },
    ],
  },
  {
    key: "video_format",
    question: "Que tipo de v?deo voc? mais gosta de criar?",
    options: [
      { value: "educational", label: "Educacional / Dicas", icon: BookOpen },
      { value: "storytelling", label: "Storytelling / Hist?rias", icon: MessageCircle },
      { value: "opinion", label: "Opini?o / Coment?rios", icon: Mic },
      { value: "behind_scenes", label: "Bastidores / Vida real", icon: Camera },
      { value: "sales", label: "Venda / Oferta / Convite", icon: Megaphone },
      { value: "mixed", label: "Misturo v?rios formatos", icon: Shuffle },
    ],
  },
  {
    key: "video_duration",
    question: "Qual ? a dura??o ideal dos seus v?deos?",
    options: [
      { value: "1min", label: "At? 1 minuto", icon: Timer },
      { value: "2min", label: "2 minutos", icon: Clock },
      { value: "3min", label: "3 minutos", icon: Clock },
      { value: "5min", label: "5 minutos", icon: Timer },
      { value: "10min_plus", label: "+10 min", icon: BatteryFull },
    ],
  },
  {
    key: "platforms",
    question: "Onde voc? pretende publicar seus v?deos?",
    multiSelect: true,
    options: [
      { value: "instagram", label: "Instagram (Reels / Stories)", icon: Camera },
      { value: "tiktok", label: "TikTok", icon: Music },
      { value: "youtube_shorts", label: "YouTube Shorts", icon: PlayCircle },
      { value: "youtube_long", label: "YouTube (v?deos longos)", icon: Video },
      { value: "lives", label: "Lives", icon: Radio },
      { value: "other", label: "Outras plataformas", icon: Globe },
    ],
  },
  {
    key: "speaking_tone",
    question: "Qual ? o tom da sua fala nos v?deos?",
    options: [
      { value: "professional", label: "Profissional / Autoridade", icon: Briefcase },
      { value: "friendly", label: "Amig?vel / Conversa informal", icon: Smile },
      { value: "motivational", label: "Motivacional / Inspirador", icon: Sparkles },
      { value: "fun", label: "Divertido / Descontra?do", icon: Smile },
      { value: "direct", label: "Direto ao ponto", icon: ArrowRight },
    ],
  },
  {
    key: "energy_level",
    question: "Qual ? o n?vel de energia dos seus v?deos?",
    options: [
      { value: "low", label: "Baixo (calmo, reflexivo)", icon: BatteryLow },
      { value: "medium", label: "M?dio (equilibrado)", icon: BatteryMedium },
      { value: "high", label: "Alto (animado, intenso)", icon: BatteryFull },
    ],
  },
  {
    key: "content_goal",
    question: "Qual ? o objetivo principal dos seus v?deos hoje?",
    options: [
      { value: "inform", label: "Informar (compartilhar not?cias)", icon: Info },
      { value: "educate", label: "Educar (Ensinar conceitos)", icon: BookOpen },
      { value: "entertain", label: "Entreter (Divertir audi?ncia)", icon: Smile },
      { value: "inspire", label: "Inspirar (Motivar Pessoas)", icon: Star },
      { value: "sell", label: "Vender (Promover produtos)", icon: ShoppingCart },
      { value: "engage", label: "Engajar (Criar comunidade)", icon: Users },
    ],
  },
];
