import {
  Award,
  Baby,
  BadgeCheck,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Calendar,
  Camera,
  Clock,
  Goal,
  Film,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  HelpCircle,
  List,
  Lightbulb,
  Megaphone,
  MessageCircle,
  Mic,
  MicOff,
  Music,
  Newspaper,
  PlayCircle,
  Radio,
  Shuffle,
  Smile,
  Sparkles,
  Star,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  UserCheck,
  Video,
  Volume2,
  Zap,
  BatteryLow,
  BatteryMedium,
  BatteryFull,
  ArrowRight,
  Eye,
  Frown,
  Meh,
  ShoppingCart,
  Info,
  FileText,
  Share2,
  Target,
  Building2,
} from "lucide-react";

export interface QuizOption {
  value: string;
  label: string;
  icon?: any;
}

export interface QuizQuestionData {
  key: string;
  question: string;
  subtitle?: string;
  icon?: any;
  options: QuizOption[];
  multiSelect?: boolean;
}

export const QUIZ_QUESTIONS: QuizQuestionData[] = [
  {
    key: "age_range",
    question: "Quantos anos você tem?",
    options: [
      { value: "under_18", label: "Menor de 18 anos", icon: Baby },
      { value: "18_24", label: "18-24", icon: GraduationCap },
      { value: "25_34", label: "25-34", icon: Briefcase },
      { value: "35_44", label: "35-44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "main_goal",
    question: "Qual é o seu principal objetivo com vídeos nas redes sociais?",
    subtitle: "Escolha o que mais se aplica a você",
    icon: Target,
    options: [
      { value: "grow_audience", label: "Crescer minha audiência", icon: TrendingUp },
      { value: "engage_community", label: "Engajar minha comunidade", icon: Users },
      { value: "sell_products", label: "Vender produtos/serviços", icon: BriefcaseBusiness },
      { value: "share_knowledge", label: "Compartilhar conhecimentos", icon: Lightbulb },
    ],
  },
  {
    key: "publish_frequency",
    question: "Com que frequência você publica vídeos atualmente?",
    icon: Calendar,
    options: [
      { value: "daily", label: "Diariamente", icon: Calendar },
      { value: "3_5_weekly", label: "3-5 vezes por semana", icon: Clock },
      { value: "1_2_weekly", label: "1-2 vezes por semana", icon: Timer },
      { value: "rarely", label: "Quase nunca", icon: BatteryLow },
    ],
  },
  {
    key: "comfort_recording",
    question: "Como você se sente ao gravar vídeos?",
    icon: Mic,
    multiSelect: true,
    options: [
      { value: "very_comfortable", label: "Muito confortável", icon: Smile },
      { value: "ok_insecure", label: "OK, mas fico inseguro às vezes", icon: Meh },
      { value: "freeze_lose_words", label: "Costumo travar ou perder palavras", icon: Frown },
      { value: "avoid", label: "Evito gravar sempre que posso", icon: MicOff },
    ],
  },
  {
    key: "biggest_challenge",
    question: "Qual é o maior desafio que você enfrenta hoje com vídeos?",
    subtitle: "Identificar isso nos ajuda a personalizar seu plano",
    options: [
      { value: "lack_ideas", label: "Faltar ideias de conteúdo", icon: Lightbulb },
      { value: "poor_editing", label: "Não saber editar bem", icon: Film },
      { value: "no_engagement", label: "Não conseguir engajar o público", icon: Users },
      { value: "shyness", label: "Timidez / falta de confiança ao falar", icon: Mic },
    ],
  },
  {
    key: "planning_style",
    question: "Como você planeja seus vídeos?",
    icon: FileText,
    options: [
      { value: "full_scripts", label: "Faço roteiros completos", icon: FileText },
      { value: "loose_topics", label: "Tenho apenas tópicos soltos", icon: List },
      { value: "no_script", label: "Vou gravando sem roteiro", icon: Video },
      { value: "want_to_learn", label: "Quero aprender a planejar conteúdo", icon: BookOpen },
    ],
  },
  {
    key: "editing_time",
    question: "Quanto tempo você dedica à edição?",
    icon: Clock,
    options: [
      { value: "less_30min", label: "Menos de 30 min por vídeo", icon: Timer },
      { value: "30min_1h", label: "30 min - 1h", icon: Clock },
      { value: "1_2h", label: "1-2h", icon: BatteryMedium },
      { value: "more_2h", label: "Mais de 2h", icon: BatteryFull },
    ],
  },
  {
    key: "result_goal",
    question: "Qual resultado você quer ver nos próximos 3 meses?",
    icon: TrendingUp,
    multiSelect: true,
    options: [
      { value: "more_followers", label: "+ Seguidores", icon: TrendingUp },
      { value: "more_views", label: "+ Visualizações", icon: Eye },
      { value: "more_engagement", label: "Maior engajamento", icon: Heart },
      { value: "more_messages_sales", label: "Receber mais mensagens/vendas", icon: MessageCircle },
    ],
  },
  {
    key: "niche",
    question: "Qual é o seu nicho principal?",
    icon: Briefcase,
    options: [
      { value: "education", label: "Educação / Conteúdo informativo", icon: BookOpen },
      { value: "business", label: "Negócios / Marketing / Vendas", icon: BriefcaseBusiness },
      { value: "lifestyle", label: "Lifestyle / Rotina / Vlogs", icon: Heart },
      { value: "health", label: "Saúde / Fitness / Bem-estar", icon: HeartPulse },
      { value: "entertainment", label: "Entretenimento / Humor", icon: Film },
      { value: "other", label: "Outro / Ainda estou definindo", icon: Sparkles },
    ],
  },
  {
    key: "creator_level",
    question: "Qual é o seu nível como criador de conteúdo?",
    icon: Award,
    options: [
      { value: "beginner", label: "Iniciante (começando na área)", icon: Trophy },
      { value: "basic", label: "Básico (já postei alguns vídeos)", icon: Award },
      { value: "intermediate", label: "Intermediário (posto com frequência)", icon: Star },
      { value: "advanced", label: "Avançado (crio conteúdo profissionalmente)", icon: BadgeCheck },
    ],
  },
  {
    key: "audience_type",
    question: "Quem é sua audiência principal?",
    icon: UserCheck,
    options: [
      { value: "b2c", label: "Pessoas físicas (B2C)", icon: Users },
      { value: "entrepreneurs", label: "Empreendedores / Profissionais", icon: BriefcaseBusiness },
      { value: "creators", label: "Criadores de conteúdo", icon: Sparkles },
      { value: "b2b", label: "Empresas (B2B)", icon: Building2 },
      { value: "general", label: "Público geral", icon: Globe },
    ],
  },
  {
    key: "audience_age",
    question: "Qual é a faixa etária do seu público?",
    icon: Users,
    options: [
      { value: "under_18", label: "Menor de 18 anos", icon: Baby },
      { value: "18_24", label: "18-24", icon: GraduationCap },
      { value: "25_34", label: "25-34", icon: Briefcase },
      { value: "35_44", label: "35-44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "audience_gender",
    question: "Como é a distribuição de gênero do seu público?",
    icon: Heart,
    options: [
      { value: "mostly_female", label: "Majoritariamente feminino", icon: Heart },
      { value: "mostly_male", label: "Majoritariamente masculino", icon: UserCheck },
      { value: "balanced", label: "Bem equilibrado", icon: Users },
      { value: "unknown", label: "Ainda não sei", icon: HelpCircle },
    ],
  },
  {
    key: "video_format",
    question: "Que tipo de vídeo você mais gosta de criar?",
    icon: Film,
    options: [
      { value: "educational", label: "Educacional / Dicas", icon: BookOpen },
      { value: "storytelling", label: "Storytelling / Histórias", icon: MessageCircle },
      { value: "opinion", label: "Opinião / Comentários", icon: Mic },
      { value: "behind_scenes", label: "Bastidores / Vida real", icon: Camera },
      { value: "sales", label: "Venda / Oferta / Convite", icon: Megaphone },
      { value: "mixed", label: "Misturo vários formatos", icon: Shuffle },
    ],
  },
  {
    key: "video_duration",
    question: "Qual é a duração ideal dos seus vídeos?",
    icon: Timer,
    options: [
      { value: "1min", label: "Até 1 minuto", icon: Timer },
      { value: "2min", label: "2 minutos", icon: Clock },
      { value: "3min", label: "3 minutos", icon: Clock },
      { value: "5min", label: "5 minutos", icon: Timer },
      { value: "10min_plus", label: "+10 min", icon: BatteryFull },
    ],
  },
  {
    key: "platforms",
    question: "Onde você publica (ou pretende publicar) seus vídeos?",
    subtitle: "Pode selecionar mais de uma opção",
    icon: Share2,
    multiSelect: true,
    options: [
      { value: "instagram", label: "Instagram (Reels / Stories)", icon: Camera },
      { value: "tiktok", label: "TikTok", icon: Music },
      { value: "youtube_shorts", label: "YouTube Shorts", icon: PlayCircle },
      { value: "youtube_long", label: "YouTube (vídeos longos)", icon: Video },
      { value: "lives", label: "Lives", icon: Radio },
      { value: "other", label: "Outras plataformas", icon: Globe },
    ],
  },
  {
    key: "speaking_tone",
    question: "Qual é o tom da sua fala nos vídeos?",
    icon: Volume2,
    options: [
      { value: "professional", label: "Profissional / Autoridade", icon: Briefcase },
      { value: "friendly", label: "Amigável / Conversa informal", icon: Smile },
      { value: "motivational", label: "Motivacional / Inspirador", icon: Sparkles },
      { value: "fun", label: "Divertido / Descontraído", icon: Smile },
      { value: "direct", label: "Direto ao ponto", icon: ArrowRight },
    ],
  },
  {
    key: "energy_level",
    question: "Qual é o nível de energia dos seus vídeos?",
    icon: Zap,
    options: [
      { value: "low", label: "Baixo (calmo, reflexivo)", icon: BatteryLow },
      { value: "medium", label: "Médio (equilibrado)", icon: BatteryMedium },
      { value: "high", label: "Alto (animado, intenso)", icon: BatteryFull },
    ],
  },
  {
    key: "content_goal",
    question: "Qual é o objetivo principal dos seus vídeos hoje?",
    icon: Goal,
    options: [
      { value: "inform", label: "Informar (compartilhar notícias)", icon: Info },
      { value: "educate", label: "Educar (Ensinar conceitos)", icon: BookOpen },
      { value: "entertain", label: "Entreter (Divertir audiência)", icon: Smile },
      { value: "inspire", label: "Inspirar (Motivar Pessoas)", icon: Star },
      { value: "sell", label: "Vender (Promover produtos)", icon: ShoppingCart },
      { value: "engage", label: "Engajar (Criar comunidade)", icon: Users },
    ],
  },
];
