import {
  ArrowRight,
  Award,
  Baby,
  BadgeCheck,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Briefcase,
  BriefcaseBusiness,
  BookOpen,
  Building2,
  Camera,
  Clock,
  Eye,
  FileText,
  Film,
  Frown,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  HelpCircle,
  Info,
  Lightbulb,
  List,
  Megaphone,
  MessageCircle,
  Mic,
  MicOff,
  Meh,
  Music,
  PlayCircle,
  Radio,
  Shuffle,
  Smile,
  Sparkles,
  Star,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  UserCheck,
  Video,
  Volume2,
  Zap,
  ShoppingCart,
} from "lucide-react";

import { QuizQuestionData } from "./quizTypes";

export const QUIZ_QUESTIONS: QuizQuestionData[] = [
  {
    key: "age_range",
    question: "Quantos anos você tem?",
    options: [
      { value: "under_18", label: "Até 18 anos", icon: Baby },
      { value: "18_24", label: "18-24", icon: GraduationCap },
      { value: "25_34", label: "25-34", icon: Briefcase },
      { value: "35_44", label: "35-44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "gender",
    question: "Qual o seu gênero?",
    options: [
      { value: "woman", label: "Mulher", icon: Heart },
      { value: "man", label: "Homem", icon: UserCheck },
      { value: "non_binary", label: "Não-binário", icon: Users },
      { value: "prefer_not", label: "Prefiro não informar", icon: HelpCircle },
    ],
  },
  {
    key: "main_goal",
    question: "Qual é o seu principal objetivo?",
    options: [
      { value: "more_followers", label: "+ Seguidores", icon: TrendingUp },
      { value: "more_views", label: "+ Visualizações", icon: Eye },
      { value: "more_engagement", label: "Maior engajamento", icon: Heart },
      { value: "more_messages_sales", label: "Receber mais mensagens/vendas", icon: MessageCircle },
    ],
  },
  {
    key: "comfort_recording",
    question: "Como você se sente ao gravar vídeos?",
    options: [
      { value: "sometimes_insecure", label: "Às vezes fico inseguro", icon: Meh },
      { value: "freeze_lose_words", label: "Costumo travar ou perder palavras", icon: Frown },
      { value: "avoid", label: "Evito gravar sempre que posso", icon: MicOff },
      { value: "very_uncomfortable", label: "Muito desconfortável", icon: BatteryLow },
    ],
  },
  {
    key: "biggest_challenge",
    question: "Qual é o maior desafio que você enfrenta hoje com vídeos?",
    options: [
      { value: "lack_ideas", label: "Faltar ideias de conteúdo", icon: Lightbulb },
      { value: "poor_editing", label: "Não saber editar bem", icon: Film },
      { value: "no_engagement", label: "Não conseguir engajar o público", icon: Users },
      { value: "shyness", label: "Timidez / falta de confiança ao falar", icon: Mic },
    ],
  },
  {
    key: "planning_style",
    question: "Como você planeja seus vídeos?",
    options: [
      { value: "no_technique", label: "Faço roteiros sem técnica", icon: FileText },
      { value: "loose_topics", label: "Tenho apenas tópicos soltos", icon: List },
      { value: "no_script", label: "Vou gravando sem roteiro", icon: Video },
      { value: "watch_others", label: "Vejo outros vídeos", icon: PlayCircle },
    ],
  },
  {
    key: "editing_time",
    question: "Quanto tempo você dedica à gravação?",
    options: [
      { value: "less_30min", label: "Menos de 30 min por vídeo", icon: Timer },
      { value: "30min_1h", label: "30 min - 1h", icon: Clock },
      { value: "1_2h", label: "1-2h", icon: BatteryMedium },
      { value: "more_2h", label: "Mais de 2h", icon: BatteryFull },
    ],
  },
  {
    key: "niche",
    question: "Sobre o que você gosta de falar?",
    freeText: true,
    freeTextPlaceholder: "Ex: Tecnologia, Marketing, Culinária, Fitness...",
    options: [],
  },
  {
    key: "creator_level",
    question: "Qual é o seu nível como criador de conteúdo?",
    options: [
      { value: "beginner", label: "Iniciante (começando na área)", icon: Trophy },
      { value: "basic", label: "Básico (já postei alguns vídeos)", icon: Award },
      { value: "intermediate", label: "Intermediário (posto com frequência)", icon: Star },
      { value: "advanced", label: "Avançado (crio conteúdo profissionalmente)", icon: BadgeCheck },
    ],
  },
  {
    key: "audience_type",
    question: "Quem é sua audiência principal?",
    options: [
      { value: "b2c", label: "Pessoas físicas (B2C)", icon: Users },
      { value: "entrepreneurs", label: "Empreendedores / Profissionais", icon: BriefcaseBusiness },
      { value: "creators", label: "Criadores de conteúdo", icon: Sparkles },
      { value: "b2b", label: "Empresas (B2B)", icon: Building2 },
      { value: "general", label: "Público geral", icon: Globe },
    ],
  },
  {
    key: "audience_age",
    question: "Qual é a faixa etária do seu público?",
    options: [
      { value: "under_18", label: "Até 18 anos", icon: Baby },
      { value: "18_24", label: "18-24", icon: GraduationCap },
      { value: "25_34", label: "25-34", icon: Briefcase },
      { value: "35_44", label: "35-44", icon: Users },
      { value: "45_plus", label: "45+", icon: UserCheck },
    ],
  },
  {
    key: "audience_gender",
    question: "Como é a distribuição de gênero do seu público?",
    options: [
      { value: "mostly_female", label: "Majoritariamente feminino", icon: Heart },
      { value: "mostly_male", label: "Majoritariamente masculino", icon: UserCheck },
      { value: "balanced", label: "Bem equilibrado", icon: Users },
      { value: "unknown", label: "Ainda não sei", icon: HelpCircle },
    ],
  },
  {
    key: "video_format",
    question: "Que tipo de vídeo você mais gosta de criar?",
    options: [
      { value: "educational", label: "Educacional / Dicas", icon: BookOpen },
      { value: "storytelling", label: "Storytelling / Histórias", icon: MessageCircle },
      { value: "opinion", label: "Opinião / Comentários", icon: Mic },
      { value: "behind_scenes", label: "Bastidores / Vida real", icon: Camera },
      { value: "sales", label: "Venda / Oferta / Convite", icon: Megaphone },
      { value: "mixed", label: "Misturo vários formatos", icon: Shuffle },
    ],
  },
  {
    key: "video_duration",
    question: "Qual é a duração ideal dos seus vídeos?",
    options: [
      { value: "1min", label: "Até 1 minuto", icon: Timer },
      { value: "2min", label: "2 minutos", icon: Clock },
      { value: "3min", label: "3 minutos", icon: Clock },
      { value: "5min", label: "5 minutos", icon: Timer },
      { value: "10min_plus", label: "+10 min", icon: BatteryFull },
    ],
  },
  {
    key: "platforms",
    question: "Qual é a sua PRINCIPAL plataforma para publicação de vídeos?",
    options: [
      { value: "instagram", label: "Instagram (Reels / Stories)", icon: Camera },
      { value: "tiktok", label: "TikTok", icon: Music },
      { value: "youtube_shorts", label: "YouTube Shorts", icon: PlayCircle },
      { value: "youtube_long", label: "YouTube (vídeos longos)", icon: Video },
      { value: "lives", label: "Lives", icon: Radio },
      { value: "other", label: "Outras plataformas", icon: Globe },
    ],
  },
  {
    key: "speaking_tone",
    question: "Qual é o tom da sua fala nos vídeos?",
    options: [
      { value: "professional", label: "Profissional / Autoridade", icon: Briefcase },
      { value: "friendly", label: "Amigável / Conversa informal", icon: Smile },
      { value: "motivational", label: "Motivacional / Inspirador", icon: Sparkles },
      { value: "fun", label: "Divertido / Descontraído", icon: Smile },
      { value: "direct", label: "Direto ao ponto", icon: ArrowRight },
    ],
  },
  {
    key: "energy_level",
    question: "Qual é o nível de energia dos seus vídeos?",
    options: [
      { value: "low", label: "Baixo (calmo, reflexivo)", icon: BatteryLow },
      { value: "medium", label: "Médio (equilibrado)", icon: BatteryMedium },
      { value: "high", label: "Alto (animado, intenso)", icon: BatteryFull },
    ],
  },
  {
    key: "content_goal",
    question: "Qual é o objetivo principal dos seus vídeos hoje?",
    options: [
      { value: "inform", label: "Informar (compartilhar notícias)", icon: Info },
      { value: "educate", label: "Educar (Ensinar conceitos)", icon: BookOpen },
      { value: "entertain", label: "Entreter (Divertir audiência)", icon: Smile },
      { value: "inspire", label: "Inspirar (Motivar Pessoas)", icon: Star },
      { value: "sell", label: "Vender (Promover produtos)", icon: ShoppingCart },
      { value: "engage", label: "Engajar (Criar comunidade)", icon: Users },
    ],
  },
];
